import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useSession, signIn, signOut } from 'next-auth/react';



const Home: NextPage = () => {

  const { data, status } = useSession();

  console.log('data: ', data);
  console.log('status: ', status);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      HomePage!

      <button onClick={() => signIn(undefined)}>
        SignIn
      </button>
    </div>
  )
}

export default Home
